#!/bin/bash
version=`python3 -c "import electrum_doge.electrum; print(electrum_doge.electrum.version.ELECTRUM_VERSION)"`
sig=`./run_electrum_doge -o signmessage $SIGNING_ADDRESS $version -w $SIGNING_WALLET`
echo "{ \"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}"
